# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
      - image: circleci/mysql:8.0.12
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=test
          - MYSQL_DATABASE=test_fr

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements" }}

      - run:
          name: setup database
          command: |
            mysql -u root -e "CREATE DATABASE IF NOT EXISTS test_fr"

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export CONFIG=configs.test.Test
            flask db upgrade
            pytest --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
