"""Init

Revision ID: 8a2c044d5700
Revises:
Create Date: 2018-09-29 02:04:17.469538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2c044d5700'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot', sa.String(length=150), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_event_robot'), 'location_event', ['robot'], unique=False)
    op.create_index(op.f('ix_location_event_timestamp'), 'location_event', ['timestamp'], unique=False)
    op.create_table('robot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_external_id'), 'robot', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robot_external_id'), table_name='robot')
    op.drop_table('robot')
    op.drop_index(op.f('ix_location_event_timestamp'), table_name='location_event')
    op.drop_index(op.f('ix_location_event_robot'), table_name='location_event')
    op.drop_table('location_event')
    # ### end Alembic commands ###
