"""Initial

Revision ID: 9c586b57b7e5
Revises: 
Create Date: 2018-10-12 17:33:20.670490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c586b57b7e5'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot', sa.String(length=150), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_event_robot'), 'location_event', ['robot'], unique=False)
    op.create_index(op.f('ix_location_event_timestamp'), 'location_event', ['timestamp'], unique=False)
    op.create_table('robot',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('odometer', sa.Float(), nullable=False),
    sa.Column('last_x', sa.Float(), nullable=False),
    sa.Column('last_y', sa.Float(), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('removed_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_event_id'], ['location_event.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_robot_removed_time'), 'robot', ['removed_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robot_removed_time'), table_name='robot')
    op.drop_table('robot')
    op.drop_index(op.f('ix_location_event_timestamp'), table_name='location_event')
    op.drop_index(op.f('ix_location_event_robot'), table_name='location_event')
    op.drop_table('location_event')
    # ### end Alembic commands ###
